# Generated by Django 4.2 on 2023-04-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vagas",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
